/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guilhermeguia
 */
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import static javafx.scene.input.KeyCode.R;
import javax.swing.JTextField;

public class principalForm extends javax.swing.JFrame {

    /**
     * Creates new form principalForm
     */
    
    public static int flagStopAll = 0;
    public static int flagCdTimerRunning = 0;
    public principalForm() {
        initComponents();
        lRemainder.setVisible(false);
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/img/AloeCookie.png"));
        jFirstFoodIcon.setIcon(icon);
        jSecondFoodIcon.setIcon(icon);
        jThirdFoodIcon.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jFoodPanel = new javax.swing.JPanel();
        lSelect = new java.awt.Label();
        lRemainder = new javax.swing.JLabel();
        jFirstFoodIcon = new javax.swing.JLabel();
        cbFirstFood = new javax.swing.JComboBox<>();
        tfFirstFoodClock = new javax.swing.JTextField();
        bAteFirstFood = new java.awt.Button();
        bAteSecondFood = new java.awt.Button();
        tfSecondFoodClock = new javax.swing.JTextField();
        cbSecondFood = new javax.swing.JComboBox<>();
        jSecondFoodIcon = new javax.swing.JLabel();
        lSelect1 = new java.awt.Label();
        lSelect2 = new java.awt.Label();
        jThirdFoodIcon = new javax.swing.JLabel();
        cbThirdFood = new javax.swing.JComboBox<>();
        tfThirdFoodClock = new javax.swing.JTextField();
        bStopAll1 = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        bStopAll = new java.awt.Button();
        tfCdClock = new javax.swing.JTextField();
        jStopWatchPanel = new javax.swing.JPanel();
        lHowTo1 = new java.awt.Label();
        tfStopwatch1 = new javax.swing.JTextField();
        tfStopwatch2 = new javax.swing.JTextField();
        tfStopwatch3 = new javax.swing.JTextField();
        tfStopwatch4 = new javax.swing.JTextField();
        tfStopwatch5 = new javax.swing.JTextField();
        bStart1 = new javax.swing.JButton();
        bStop1 = new javax.swing.JButton();
        bRestart1 = new javax.swing.JButton();
        bStart2 = new javax.swing.JButton();
        bStop2 = new javax.swing.JButton();
        bRestart2 = new javax.swing.JButton();
        bStart3 = new javax.swing.JButton();
        bStop3 = new javax.swing.JButton();
        bRestart3 = new javax.swing.JButton();
        bStart4 = new javax.swing.JButton();
        bStop4 = new javax.swing.JButton();
        bRestart4 = new javax.swing.JButton();
        bStart5 = new javax.swing.JButton();
        bStop5 = new javax.swing.JButton();
        bRestart5 = new javax.swing.JButton();
        tfStopwatch6 = new javax.swing.JTextField();
        bStart6 = new javax.swing.JButton();
        bStop6 = new javax.swing.JButton();
        bRestart6 = new javax.swing.JButton();
        jOgrePanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanelMenu = new javax.swing.JPanel();
        bFood = new javax.swing.JButton();
        bStopwatch = new javax.swing.JButton();
        bOgre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMainPanel.setLayout(new java.awt.CardLayout());

        lSelect.setText("1 - Select your food from the list.");

        lRemainder.setForeground(new java.awt.Color(255, 0, 0));
        lRemainder.setText("You should eat: ");
        lRemainder.setName("lRemainder"); // NOI18N

        jFirstFoodIcon.setMaximumSize(new java.awt.Dimension(42, 42));
        jFirstFoodIcon.setMinimumSize(new java.awt.Dimension(42, 42));

        cbFirstFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aloe Cookie[30]", "Aloe Yogurt[30]", "Arehaza Special[90]", "Assorted Side Dishes[90]", "Balenos Special[90]", "Beehive Cookie[90]", "Boiled Bird Eggs[30]", "Borscht[60]", "Butter-Roasted Lobster[60]", "Calpheon Special[90]", "Cheese Gratin[90]", "Coconut Cocktails[60]", "Coconut Fried Fish[60]", "Coconut Pasta[60]", "Couscous[110]", "Dark Pudding[90]", "Date Palms Wine[90]", "Desert Dumpling[30]", "Exotic Herbal Wine[30]", "Fig Pie[60]", "Fish Fillet Salad[60]", "Fish Soup[60]", "Fried Bird[60]", "Fried Vegetables[30]", "Fruit and Vegetable Salad[60]", "Fruit Juice[30]", "Fruit Pie[90]", "Fruit Pudding[30]", "Fruit Wine[60]", "Grain Soup[30]", "Grilled Sausage[30]", "Grilled Scorpion[90]", "Ham Sandwich[90]", "Honey Wine[60]", "Hunter's Salad[30]", "Healthy Sute Tea[110]", "Jungle Hamburger[110]", "Khalk's Fermented Wine[60]", "Knight Combat Rations[120]", "Lean Meat Salad[90]", "Lizard Kebab[30]", "Margoria Seafood Extravaganza[90]", "Meat Croquette[90]", "Meat Pasta[60]", "Meat Pie[60]", "Meat Sandwich[90]", "Meat Soup[30]", "Meat Stew[30]", "Mediah Special[90]", "Milk Tea[90]", "Omelet[60]", "Pickled Fish[60]", "Pickled Vegetables[60]", "Pistachio Rice[90]", "Prawn Salad[60]", "Seafood Grilled with Butter[30]", "Seafood Mushroom Salad[30]", "Seafood Pasta[60]", "Serendia Special[90]", "Smoked Fish Steak[60]", "Soft Bread[30]", "Steak[60]", "Steamed Bird[60]", "Steamed Fish[30]", "Steamed Prawn[60]", "Steamed Seafood[60]", "Steamed Whale Meat[75]", "Stir-fried Gazelle Hind Leg[60]", "Stir-Fried Meat[60]", "Stir-Fried Oyster[60]", "Stir-Fried Seafood[30]", "Stir-fried Vegetables[30]", "Sute Tea[90]", "Tea With Fine Scent[60]", "Teff Bread[110]", "Teff Sandwich[110]", "Valencian Special[120]", "Whale Meat Salad[75]" }));
        cbFirstFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFirstFoodActionPerformed(evt);
            }
        });

        tfFirstFoodClock.setEditable(false);
        tfFirstFoodClock.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tfFirstFoodClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFirstFoodClock.setText("00:00:00");
        tfFirstFoodClock.setEnabled(false);
        tfFirstFoodClock.setName("firstFoodClock"); // NOI18N
        tfFirstFoodClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstFoodClockActionPerformed(evt);
            }
        });

        bAteFirstFood.setActionCommand("n");
        bAteFirstFood.setLabel("Ate the food");
        bAteFirstFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAteFirstFoodActionPerformed(evt);
            }
        });

        bAteSecondFood.setActionCommand("n");
        bAteSecondFood.setLabel("Ate the food");
        bAteSecondFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAteSecondFoodActionPerformed(evt);
            }
        });

        tfSecondFoodClock.setEditable(false);
        tfSecondFoodClock.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tfSecondFoodClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSecondFoodClock.setText("00:00:00");
        tfSecondFoodClock.setEnabled(false);
        tfSecondFoodClock.setName("firstFoodClock"); // NOI18N
        tfSecondFoodClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondFoodClockActionPerformed(evt);
            }
        });

        cbSecondFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aloe Cookie[30]", "Aloe Yogurt[30]", "Arehaza Special[90]", "Assorted Side Dishes[90]", "Balenos Special[90]", "Beehive Cookie[90]", "Boiled Bird Eggs[30]", "Borscht[60]", "Butter-Roasted Lobster[60]", "Calpheon Special[90]", "Cheese Gratin[90]", "Coconut Cocktails[60]", "Coconut Fried Fish[60]", "Coconut Pasta[60]", "Couscous[110]", "Dark Pudding[90]", "Date Palms Wine[90]", "Desert Dumpling[30]", "Exotic Herbal Wine[30]", "Fig Pie[60]", "Fish Fillet Salad[60]", "Fish Soup[60]", "Fried Bird[60]", "Fried Vegetables[30]", "Fruit and Vegetable Salad[60]", "Fruit Juice[30]", "Fruit Pie[90]", "Fruit Pudding[30]", "Fruit Wine[60]", "Grain Soup[30]", "Grilled Sausage[30]", "Grilled Scorpion[90]", "Ham Sandwich[90]", "Honey Wine[60]", "Hunter's Salad[30]", "Healthy Sute Tea[110]", "Jungle Hamburger[110]", "Khalk's Fermented Wine[60]", "Knight Combat Rations[120]", "Lean Meat Salad[90]", "Lizard Kebab[30]", "Margoria Seafood Extravaganza[90]", "Meat Croquette[90]", "Meat Pasta[60]", "Meat Pie[60]", "Meat Sandwich[90]", "Meat Soup[30]", "Meat Stew[30]", "Mediah Special[90]", "Milk Tea[90]", "Omelet[60]", "Pickled Fish[60]", "Pickled Vegetables[60]", "Pistachio Rice[90]", "Prawn Salad[60]", "Seafood Grilled with Butter[30]", "Seafood Mushroom Salad[30]", "Seafood Pasta[60]", "Serendia Special[90]", "Smoked Fish Steak[60]", "Soft Bread[30]", "Steak[60]", "Steamed Bird[60]", "Steamed Fish[30]", "Steamed Prawn[60]", "Steamed Seafood[60]", "Steamed Whale Meat[75]", "Stir-fried Gazelle Hind Leg[60]", "Stir-Fried Meat[60]", "Stir-Fried Oyster[60]", "Stir-Fried Seafood[30]", "Stir-fried Vegetables[30]", "Sute Tea[90]", "Tea With Fine Scent[60]", "Teff Bread[110]", "Teff Sandwich[110]", "Valencian Special[120]", "Whale Meat Salad[75]" }));
        cbSecondFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSecondFoodActionPerformed(evt);
            }
        });

        jSecondFoodIcon.setMaximumSize(new java.awt.Dimension(42, 42));
        jSecondFoodIcon.setMinimumSize(new java.awt.Dimension(42, 42));

        lSelect1.setText("2 - Click on the button to when you ate the food in the game.");

        lSelect2.setText("3 - The timer will start and will remaind you witch food is ending and when you can eat again");

        jThirdFoodIcon.setMaximumSize(new java.awt.Dimension(42, 42));
        jThirdFoodIcon.setMinimumSize(new java.awt.Dimension(42, 42));

        cbThirdFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aloe Cookie[30]", "Aloe Yogurt[30]", "Arehaza Special[90]", "Assorted Side Dishes[90]", "Balenos Special[90]", "Beehive Cookie[90]", "Boiled Bird Eggs[30]", "Borscht[60]", "Butter-Roasted Lobster[60]", "Calpheon Special[90]", "Cheese Gratin[90]", "Coconut Cocktails[60]", "Coconut Fried Fish[60]", "Coconut Pasta[60]", "Couscous[110]", "Dark Pudding[90]", "Date Palms Wine[90]", "Desert Dumpling[30]", "Exotic Herbal Wine[30]", "Fig Pie[60]", "Fish Fillet Salad[60]", "Fish Soup[60]", "Fried Bird[60]", "Fried Vegetables[30]", "Fruit and Vegetable Salad[60]", "Fruit Juice[30]", "Fruit Pie[90]", "Fruit Pudding[30]", "Fruit Wine[60]", "Grain Soup[30]", "Grilled Sausage[30]", "Grilled Scorpion[90]", "Ham Sandwich[90]", "Honey Wine[60]", "Hunter's Salad[30]", "Healthy Sute Tea[110]", "Jungle Hamburger[110]", "Khalk's Fermented Wine[60]", "Knight Combat Rations[120]", "Lean Meat Salad[90]", "Lizard Kebab[30]", "Margoria Seafood Extravaganza[90]", "Meat Croquette[90]", "Meat Pasta[60]", "Meat Pie[60]", "Meat Sandwich[90]", "Meat Soup[30]", "Meat Stew[30]", "Mediah Special[90]", "Milk Tea[90]", "Omelet[60]", "Pickled Fish[60]", "Pickled Vegetables[60]", "Pistachio Rice[90]", "Prawn Salad[60]", "Seafood Grilled with Butter[30]", "Seafood Mushroom Salad[30]", "Seafood Pasta[60]", "Serendia Special[90]", "Smoked Fish Steak[60]", "Soft Bread[30]", "Steak[60]", "Steamed Bird[60]", "Steamed Fish[30]", "Steamed Prawn[60]", "Steamed Seafood[60]", "Steamed Whale Meat[75]", "Stir-fried Gazelle Hind Leg[60]", "Stir-Fried Meat[60]", "Stir-Fried Oyster[60]", "Stir-Fried Seafood[30]", "Stir-fried Vegetables[30]", "Sute Tea[90]", "Tea With Fine Scent[60]", "Teff Bread[110]", "Teff Sandwich[110]", "Valencian Special[120]", "Whale Meat Salad[75]" }));
        cbThirdFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThirdFoodActionPerformed(evt);
            }
        });

        tfThirdFoodClock.setEditable(false);
        tfThirdFoodClock.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tfThirdFoodClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfThirdFoodClock.setText("00:00:00");
        tfThirdFoodClock.setEnabled(false);
        tfThirdFoodClock.setName("firstFoodClock"); // NOI18N
        tfThirdFoodClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThirdFoodClockActionPerformed(evt);
            }
        });

        bStopAll1.setActionCommand("n");
        bStopAll1.setLabel("Ate the food");
        bStopAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopAll1ActionPerformed(evt);
            }
        });

        label2.setText("4 - If you want to stop all the food, just click \"Stop All\".");

        label3.setText("5 - The timer next to \"Stop All\" Is the Cooldown to use another food.");

        bStopAll.setActionCommand("n");
        bStopAll.setLabel("Stop All");
        bStopAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopAllActionPerformed(evt);
            }
        });

        tfCdClock.setEditable(false);
        tfCdClock.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tfCdClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCdClock.setText("00:00:00");
        tfCdClock.setEnabled(false);
        tfCdClock.setName("firstFoodClock"); // NOI18N
        tfCdClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCdClockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFoodPanelLayout = new javax.swing.GroupLayout(jFoodPanel);
        jFoodPanel.setLayout(jFoodPanelLayout);
        jFoodPanelLayout.setHorizontalGroup(
            jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFoodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRemainder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFoodPanelLayout.createSequentialGroup()
                        .addComponent(jFirstFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFirstFood, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(tfFirstFoodClock, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAteFirstFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFoodPanelLayout.createSequentialGroup()
                        .addComponent(jSecondFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSecondFood, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(tfSecondFoodClock, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAteSecondFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFoodPanelLayout.createSequentialGroup()
                        .addComponent(jThirdFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbThirdFood, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(tfThirdFoodClock, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bStopAll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFoodPanelLayout.createSequentialGroup()
                        .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jFoodPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(tfCdClock, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(bStopAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFoodPanelLayout.setVerticalGroup(
            jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFoodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lRemainder)
                .addGap(20, 20, 20)
                .addComponent(lSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFirstFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFoodPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbFirstFood)
                                .addComponent(tfFirstFoodClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bAteFirstFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSecondFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSecondFoodClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSecondFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bAteSecondFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jThirdFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bStopAll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfThirdFoodClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbThirdFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bStopAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCdClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMainPanel.add(jFoodPanel, "FoodPanel");

        lHowTo1.setText("1 - Select when the program should remind you that the timer is over.");

        tfStopwatch1.setEditable(false);
        tfStopwatch1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfStopwatch1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStopwatch1.setText("00:00:00");
        tfStopwatch1.setEnabled(false);
        tfStopwatch1.setName("firstFoodClock"); // NOI18N
        tfStopwatch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStopwatch1ActionPerformed(evt);
            }
        });

        tfStopwatch2.setEditable(false);
        tfStopwatch2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfStopwatch2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStopwatch2.setText("00:00:00");
        tfStopwatch2.setEnabled(false);
        tfStopwatch2.setName("firstFoodClock"); // NOI18N
        tfStopwatch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStopwatch2ActionPerformed(evt);
            }
        });

        tfStopwatch3.setEditable(false);
        tfStopwatch3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfStopwatch3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStopwatch3.setText("00:00:00");
        tfStopwatch3.setEnabled(false);
        tfStopwatch3.setName("firstFoodClock"); // NOI18N
        tfStopwatch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStopwatch3ActionPerformed(evt);
            }
        });

        tfStopwatch4.setEditable(false);
        tfStopwatch4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfStopwatch4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStopwatch4.setText("00:00:00");
        tfStopwatch4.setEnabled(false);
        tfStopwatch4.setName("firstFoodClock"); // NOI18N
        tfStopwatch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStopwatch4ActionPerformed(evt);
            }
        });

        tfStopwatch5.setEditable(false);
        tfStopwatch5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfStopwatch5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStopwatch5.setText("00:00:00");
        tfStopwatch5.setEnabled(false);
        tfStopwatch5.setName("firstFoodClock"); // NOI18N
        tfStopwatch5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStopwatch5ActionPerformed(evt);
            }
        });

        bStart1.setText("Start");
        bStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStart1ActionPerformed(evt);
            }
        });

        bStop1.setText("Stop");

        bRestart1.setText("Restart");

        bStart2.setText("Start");

        bStop2.setText("Stop");

        bRestart2.setText("Restart");

        bStart3.setText("Start");

        bStop3.setText("Stop");

        bRestart3.setText("Restart");

        bStart4.setText("Start");

        bStop4.setText("Stop");

        bRestart4.setText("Restart");

        bStart5.setText("Start");

        bStop5.setText("Stop");

        bRestart5.setText("Restart");

        tfStopwatch6.setEditable(false);
        tfStopwatch6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfStopwatch6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStopwatch6.setText("00:00:00");
        tfStopwatch6.setEnabled(false);
        tfStopwatch6.setName("firstFoodClock"); // NOI18N
        tfStopwatch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStopwatch6ActionPerformed(evt);
            }
        });

        bStart6.setText("Start");

        bStop6.setText("Stop");

        bRestart6.setText("Restart");

        javax.swing.GroupLayout jStopWatchPanelLayout = new javax.swing.GroupLayout(jStopWatchPanel);
        jStopWatchPanel.setLayout(jStopWatchPanelLayout);
        jStopWatchPanelLayout.setHorizontalGroup(
            jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lHowTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                        .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStopwatch1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStopwatch2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStopwatch3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStopwatch4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStopwatch5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStopwatch6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                                .addComponent(bStart5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStop5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRestart5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                                .addComponent(bStart4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStop4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRestart4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                                .addComponent(bStart3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStop3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRestart3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                                .addComponent(bStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStop2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRestart2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                                .addComponent(bStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStop1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRestart1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                                .addComponent(bStart6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStop6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bRestart6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jStopWatchPanelLayout.setVerticalGroup(
            jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStopWatchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lHowTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStopwatch1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bStart1)
                    .addComponent(bStop1)
                    .addComponent(bRestart1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStopwatch2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bStart2)
                    .addComponent(bStop2)
                    .addComponent(bRestart2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStopwatch3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bStart3)
                    .addComponent(bStop3)
                    .addComponent(bRestart3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStopwatch4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bStart4)
                    .addComponent(bStop4)
                    .addComponent(bRestart4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStopwatch5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bStart5)
                    .addComponent(bStop5)
                    .addComponent(bRestart5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStopwatch6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jStopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bStart6)
                        .addComponent(bStop6)
                        .addComponent(bRestart6)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jMainPanel.add(jStopWatchPanel, "StopWatch");

        label1.setText("Text to see if its ok");

        javax.swing.GroupLayout jOgrePanelLayout = new javax.swing.GroupLayout(jOgrePanel);
        jOgrePanel.setLayout(jOgrePanelLayout);
        jOgrePanelLayout.setHorizontalGroup(
            jOgrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOgrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        jOgrePanelLayout.setVerticalGroup(
            jOgrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOgrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jMainPanel.add(jOgrePanel, "OgrePanel");

        bFood.setText("Food");
        bFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFoodActionPerformed(evt);
            }
        });

        bStopwatch.setText("Stopwatch");
        bStopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopwatchActionPerformed(evt);
            }
        });

        bOgre.setText("Ogre ");
        bOgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOgreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bStopwatch)
                .addGap(156, 156, 156)
                .addComponent(bOgre)
                .addGap(31, 31, 31))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFood)
                    .addComponent(bStopwatch)
                    .addComponent(bOgre))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFoodActionPerformed
        CardLayout card = (CardLayout)jMainPanel.getLayout();
        card.show(jMainPanel, "FoodPanel");
    }//GEN-LAST:event_bFoodActionPerformed

    private void bStopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopwatchActionPerformed
        CardLayout card = (CardLayout)jMainPanel.getLayout();
        card.show(jMainPanel, "StopWatch");
    }//GEN-LAST:event_bStopwatchActionPerformed

    private void bStopAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopAll1ActionPerformed
        //Time is the string to hold what will be replaced in the textbox
        String time;
        //This label will be activate when the food get 30 min or less of duration
        String labelRemainder = "You should eat ";
        //Get The food name.
        String ThirdFoodName = cbThirdFood.getSelectedItem().toString();
        labelRemainder = labelRemainder + ThirdFoodName;
        //Debug to see if the name is getting ok
        //lRemainder.setText(labelRemainder);
        //lRemainder.setVisible(true);
        time = ThirdFoodName;
        time = time.substring(time.indexOf("[") + 1);
        time = time.substring(0, time.indexOf("]"));
        int t;
        t = Integer.parseInt(time);
        int h = t / 60;
        int m = t % 60;
        int s = 0;
        //If this flag is set to 1 it wont start the timer.
        flagStopAll = 0;
        initClock tSFood = new initClock(h,m,s);
        //tSFood.stTimer.scheduleAtFixedRate(tSFood.task, 1000, 1000);
        tfThirdFoodClock.setText(tSFood.h + ":" + tSFood.m + ":" + tSFood.s);
        cdTimer cdClock = new cdTimer();
        cdClock.cdTimer.scheduleAtFixedRate(cdClock.task, 1000, 1000);
        Timer updateText = new Timer();
        updateText.schedule(new TimerTask() {
            @Override public void run() {
                
                if(tSFood.s == 0 && tSFood.m >= 1){
                    tSFood.m--;
                    tSFood.s=60;
                }else if(tSFood.m == 0 && tSFood.h >= 1){
                    tSFood.m=60;
                    tSFood.h--;
                }
                
                tSFood.s--;
                
                tfThirdFoodClock.setText(tSFood.h + ":" + tSFood.m + ":" + tSFood.s);
                if(tSFood.h == 0 && tSFood.m == 0 && tSFood.s == 0 || flagStopAll == 1){
                    updateText.cancel();
                    String str = "00:00:00";
                    tfFirstFoodClock.setText(str);
                    tfSecondFoodClock.setText(str);
                    tfThirdFoodClock.setText(str);
                    cdClock.task.cancel();
                    tfCdClock.setText(str);
                }
                if(cdClock.clock.m == 0 && cdClock.clock.s == 0){
                    cdClock.task.cancel();
                }
            }
        }, 1000, 1000);
    }//GEN-LAST:event_bStopAll1ActionPerformed

    private void tfThirdFoodClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThirdFoodClockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThirdFoodClockActionPerformed

    private void cbThirdFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThirdFoodActionPerformed
        //Set the path to the img and fix the name.
        String foodName = cbThirdFood.getSelectedItem().toString();
        String path = "resources/img";
        path = path + "/" + foodName;
        int ini, end;
        ini = path.indexOf("[");
        end = path.indexOf("]") + 1;
        path = path.replace(path.substring(ini, end), "");
        path = path.replace(" ", "");
        path = path + ".png";
        //Just Debug
        //lRemainder.setText(path);
        //lRemainder.setVisible(true);
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(path));
        jThirdFoodIcon.setIcon(icon);
    }//GEN-LAST:event_cbThirdFoodActionPerformed

    private void cbSecondFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSecondFoodActionPerformed
        //Set the path to the img and fix the name.
        String foodName = cbSecondFood.getSelectedItem().toString();
        String path = "resources/img";
        path = path + "/" + foodName;
        int ini, end;
        ini = path.indexOf("[");
        end = path.indexOf("]") + 1;
        path = path.replace(path.substring(ini, end), "");
        path = path.replace(" ", "");
        path = path + ".png";
        //Just Debug
        //lRemainder.setText(path);
        //lRemainder.setVisible(true);
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(path));
        jSecondFoodIcon.setIcon(icon);
    }//GEN-LAST:event_cbSecondFoodActionPerformed

    private void tfSecondFoodClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondFoodClockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondFoodClockActionPerformed

    private void bAteSecondFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAteSecondFoodActionPerformed
        //Time is the string to hold what will be replaced in the textbox
        String time;
        //This label will be activate when the food get 30 min or less of duration
        String labelRemainder = "You should eat ";
        //Get The food name.
        String SecondFoodName = cbSecondFood.getSelectedItem().toString();
        labelRemainder = labelRemainder + SecondFoodName;
        lRemainder.setText(labelRemainder);
        lRemainder.setVisible(true);
        time = SecondFoodName;
        time = time.substring(time.indexOf("[") + 1);
        time = time.substring(0, time.indexOf("]"));
        int t;
        t = Integer.parseInt(time);
        int h = t / 60;
        int m = t % 60;
        int s = 0;
        //If this falg is set to 1 it wont start the timer
        flagStopAll = 0;
        initClock tSFood = new initClock(h,m,s);
        //tSFood.stTimer.scheduleAtFixedRate(tSFood.task, 1000, 1000);
        tfSecondFoodClock.setText(tSFood.h + ":" + tSFood.m + ":" + tSFood.s);
        cdTimer cdClock = new cdTimer();
        cdClock.cdTimer.scheduleAtFixedRate(cdClock.task, 1000, 1000);
        Timer updateText = new Timer();
        updateText.schedule(new TimerTask() {
            @Override public void run() {
                if(tSFood.s == 0 && tSFood.m >= 1){
                    tSFood.m--;
                    tSFood.s=60;
                }else if(tSFood.m == 0 && tSFood.h >= 1){
                    tSFood.m=60;
                    tSFood.h--;
                }
                tSFood.s--;
                tfCdClock.setText("00:" + cdClock.clock.m + ":" + cdClock.clock.s);
                tfSecondFoodClock.setText(tSFood.h + ":" + tSFood.m + ":" + tSFood.s);
                if(tSFood.h == 0 && tSFood.m == 0 && tSFood.s == 0 || flagStopAll == 1){
                    updateText.cancel();
                    String str = "00:00:00";
                    tfFirstFoodClock.setText(str);
                    tfSecondFoodClock.setText(str);
                    tfThirdFoodClock.setText(str);
                    cdClock.task.cancel();
                    tfCdClock.setText(str);
                }
                if(cdClock.clock.m == 0 && cdClock.clock.s == 0){
                    cdClock.task.cancel();
                }
            }
        }, 1000, 1000);
    }//GEN-LAST:event_bAteSecondFoodActionPerformed

    private void bAteFirstFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAteFirstFoodActionPerformed
        //Time is the string to hold what will be replaced in the textbox
        String time;
        //This label will be activate when the food get 30 min or less of duration
        String labelRemainder = "You should eat ";
        //Get The food name.
        String firstFoodName = cbFirstFood.getSelectedItem().toString();
        labelRemainder = labelRemainder + firstFoodName;
        lRemainder.setText(labelRemainder);
        lRemainder.setVisible(true);
        time = firstFoodName;
        time = time.substring(time.indexOf("[") + 1);
        time = time.substring(0, time.indexOf("]"));
        int t;
        t = Integer.parseInt(time);
        int h = t / 60;
        int m = t % 60;
        int s = 0;
        //If this flag is set to 1, the timer will not start.
        flagStopAll = 0;
        //Clocks and task to update the timer.
        initClock tSFood = new initClock(h,m,s);
        tfFirstFoodClock.setText(tSFood.h + ":" + tSFood.m + ":" + tSFood.s);
        cdTimer cdClock = new cdTimer();
        cdClock.cdTimer.scheduleAtFixedRate(cdClock.task, 1000, 1000);
        Timer updateText = new Timer();
        updateText.schedule(new TimerTask() {
            @Override public void run() {
                //Food timer
                if(tSFood.s == 0 && tSFood.m >= 1){
                    tSFood.m--;
                    tSFood.s=60;
                }else if(tSFood.m == 0 && tSFood.h >= 1){
                    tSFood.m=60;
                    tSFood.h--;
                }
                tSFood.s--;
                tfCdClock.setText("00:" + cdClock.clock.m + ":" + cdClock.clock.s);
                tfFirstFoodClock.setText(tSFood.h + ":" + tSFood.m + ":" + tSFood.s);
                if(tSFood.h == 0 && tSFood.m == 0 && tSFood.s == 0 || flagStopAll == 1){
                    updateText.cancel();
                    String str = "00:00:00";
                    tfFirstFoodClock.setText(str);
                    tfSecondFoodClock.setText(str);
                    tfThirdFoodClock.setText(str);
                    cdClock.task.cancel();
                    tfCdClock.setText(str);
                    
                }
                if(cdClock.clock.m == 0 && cdClock.clock.s == 0){
                    cdClock.task.cancel();
                }
            }
        }, 1000, 1000);
    }//GEN-LAST:event_bAteFirstFoodActionPerformed

    private void tfFirstFoodClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstFoodClockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstFoodClockActionPerformed

    private void cbFirstFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFirstFoodActionPerformed
        //Set the path to the img and fix the name.
        String foodName = cbFirstFood.getSelectedItem().toString();
        String path = "resources/img";
        path = path + "/" + foodName;
        int ini, end;
        ini = path.indexOf("[");
        end = path.indexOf("]") + 1;
        path = path.replace(path.substring(ini, end), "");
        path = path.replace(" ", "");
        path = path + ".png";
        //Just Debug
        //lRemainder.setText(path);
        //lRemainder.setVisible(true);
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(path));
        //ImageIcon icon = new ImageIcon(path);
        jFirstFoodIcon.setIcon(icon);

    }//GEN-LAST:event_cbFirstFoodActionPerformed

    private void bStopAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopAllActionPerformed
        //Flag to stop all timers;
        flagStopAll = 1;
    }//GEN-LAST:event_bStopAllActionPerformed

    private void tfCdClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCdClockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCdClockActionPerformed

    private void bOgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOgreActionPerformed
        CardLayout card = (CardLayout)jMainPanel.getLayout();
        card.show(jMainPanel, "OgrePanel");
    }//GEN-LAST:event_bOgreActionPerformed

    private void tfStopwatch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStopwatch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStopwatch1ActionPerformed

    private void tfStopwatch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStopwatch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStopwatch2ActionPerformed

    private void tfStopwatch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStopwatch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStopwatch3ActionPerformed

    private void tfStopwatch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStopwatch4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStopwatch4ActionPerformed

    private void tfStopwatch5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStopwatch5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStopwatch5ActionPerformed

    private void tfStopwatch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStopwatch6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStopwatch6ActionPerformed

    private void bStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStart1ActionPerformed
        Stopwatch clock = new Stopwatch(tfStopwatch1);
        clock.runTime.scheduleAtFixedRate(clock.task, 1000, 1000);
    }//GEN-LAST:event_bStart1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bAteFirstFood;
    private java.awt.Button bAteSecondFood;
    private javax.swing.JButton bFood;
    private javax.swing.JButton bOgre;
    private javax.swing.JButton bRestart1;
    private javax.swing.JButton bRestart2;
    private javax.swing.JButton bRestart3;
    private javax.swing.JButton bRestart4;
    private javax.swing.JButton bRestart5;
    private javax.swing.JButton bRestart6;
    private javax.swing.JButton bStart1;
    private javax.swing.JButton bStart2;
    private javax.swing.JButton bStart3;
    private javax.swing.JButton bStart4;
    private javax.swing.JButton bStart5;
    private javax.swing.JButton bStart6;
    private javax.swing.JButton bStop1;
    private javax.swing.JButton bStop2;
    private javax.swing.JButton bStop3;
    private javax.swing.JButton bStop4;
    private javax.swing.JButton bStop5;
    private javax.swing.JButton bStop6;
    private java.awt.Button bStopAll;
    private java.awt.Button bStopAll1;
    private javax.swing.JButton bStopwatch;
    private javax.swing.JComboBox<String> cbFirstFood;
    private javax.swing.JComboBox<String> cbSecondFood;
    private javax.swing.JComboBox<String> cbThirdFood;
    private javax.swing.JLabel jFirstFoodIcon;
    private javax.swing.JPanel jFoodPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jOgrePanel;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JLabel jSecondFoodIcon;
    private javax.swing.JPanel jStopWatchPanel;
    private javax.swing.JLabel jThirdFoodIcon;
    private java.awt.Label lHowTo1;
    private javax.swing.JLabel lRemainder;
    private java.awt.Label lSelect;
    private java.awt.Label lSelect1;
    private java.awt.Label lSelect2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField tfCdClock;
    private javax.swing.JTextField tfFirstFoodClock;
    private javax.swing.JTextField tfSecondFoodClock;
    private javax.swing.JTextField tfStopwatch1;
    private javax.swing.JTextField tfStopwatch2;
    private javax.swing.JTextField tfStopwatch3;
    private javax.swing.JTextField tfStopwatch4;
    private javax.swing.JTextField tfStopwatch5;
    private javax.swing.JTextField tfStopwatch6;
    private javax.swing.JTextField tfThirdFoodClock;
    // End of variables declaration//GEN-END:variables
}
          
